### ISSUE TITLE
wp_enqueue_script instead of wp_register_script

### ISSUE THREAD

**Issue by stkjj** [radgeek/fwp-keyword-filters#2]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; FWPKeywordFilters has a deprecated constructor in /var/www/wordpress/wp-content/plugins/fwp-keyword-filters/fwp-keyword-filters.php on line 106

Notice: wp_register_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in /var/www/wordpress/wp-includes/functions.php on line 4136

**Comment by stkjj** [comment]
any update on this?

**Comment by skriesch** [comment]
Bugfix is added.

**Comment by radgeek** [comment]
Hey y'all, thanks for checking this out and flagging it for my attention. I made a fix which takes a bit different approach from @skriesch 's solution above; a resolution for both the Deprecation notice @stkjj mentions and also for the wp_register_script Notice should be included in the most recent version, 2017.1007. Let me know if it works for y'all!

**Comment by stkjj** [comment]
thanks a lot - works as expected!
